import React from 'react';
import { motion } from 'framer-motion';
import { AIHiringIntelligenceDashboard } from './AIHiringIntelligenceDashboard';
import { ResumeRoastCard } from './ResumeRoastCard';
import { OverallScoreCard } from './OverallScoreCard';
import { ScoresBreakdown } from './ScoresBreakdown';
import { RadarChartCard } from './RadarChartCard';
import { ResumeMatchSection } from './ResumeMatchSection';
import { ImprovementSimulator } from './ImprovementSimulator';
import { RecruiterPersonaCard } from './RecruiterPersonaCard';
import { RecruiterNotesCard } from './RecruiterNotesCard';
import { InterviewQuestionsCard } from './InterviewQuestionsCard';
import { CompanyReadinessCard } from './CompanyReadinessCard';
import { RecruiterTimeline } from './RecruiterTimeline';
import { RecruiterFeedbackCard } from './RecruiterFeedbackCard';
import { BulletImprovementsCard } from './BulletImprovementsCard';
import { SectionAnalysisCard } from './SectionAnalysisCard';
import { ReportDownloadButton } from './ReportDownloadButton';
import { ArrowLeft } from 'lucide-react';

export const ResultsDashboard = ({ data = {}, onReset, analysisTime }) => {
  if (!data || Object.keys(data).length === 0) {
    return (
      <div className="py-20 text-center">
        <p className="text-slate-500 mb-4">No evaluation data available.</p>
        <button onClick={onReset} className="px-4 py-2 rounded-xl bg-indigo-600 text-white font-bold text-sm">
          Return to Upload
        </button>
      </div>
    );
  }

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.05,
      },
    },
  };

  const cardVariants = {
    hidden: { opacity: 0, y: 15, scale: 0.99 },
    visible: {
      opacity: 1,
      y: 0,
      scale: 1,
      transition: { duration: 0.35, ease: 'easeOut' },
    },
  };

  return (
    <motion.div
      initial="hidden"
      animate="visible"
      variants={containerVariants}
      className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-10"
    >
      {/* Action Bar Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-8 no-print">
        <button
          onClick={onReset}
          className="px-4 py-2 rounded-xl bg-white border border-slate-200 hover:bg-slate-50 text-slate-700 text-sm font-bold flex items-center gap-2 shadow-sm transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Analyze Another Resume</span>
        </button>

        <ReportDownloadButton data={data} />
      </div>

      {/* Main Report Wrapper */}
      <div id="resumeiq-results-report" className="space-y-8">
        {/* Report Header for printed version */}
        <div className="hidden print:block mb-8 border-b pb-4">
          <h1 className="text-3xl font-black text-slate-900">ResumeIQ Executive Recruiting Platform Report</h1>
          <p className="text-sm text-slate-600">Generated by Senior Tech Recruiter Engine</p>
        </div>

        {/* 1. HERO CENTERPIECE: AI Hiring Intelligence Dashboard (Gauge-free modern dashboard) */}
        <motion.div variants={cardVariants}>
          <AIHiringIntelligenceDashboard 
            decisionMeter={data.decisionMeter || {}} 
            executiveSummary={data.executiveSummary || {}} 
            confidence={data.confidence ?? 95}
            fullData={data}
            analysisTime={analysisTime}
          />
        </motion.div>

        {/* 2. 🔥 VIRAL SIGNATURE FEATURE: AI Resume Roast */}
        <motion.div variants={cardVariants}>
          <ResumeRoastCard roastData={data.resumeRoast || {}} fullData={data} />
        </motion.div>

        {/* 3. Overall Score & Readiness Verdict */}
        <motion.div variants={cardVariants}>
          <OverallScoreCard
            overallScore={data.overallScore ?? 85}
            decision={data.decision || 'Likely Interview'}
            recruiterFeedback={data.recruiterFeedback || ''}
            confidence={data.confidence ?? 95}
            analysisConfidenceReason={data.analysisConfidenceReason || ''}
            analysisTime={analysisTime}
          />
        </motion.div>

        {/* 4. Analytical Performance Breakdown */}
        <motion.div variants={cardVariants}>
          <ScoresBreakdown scores={data} />
        </motion.div>

        {/* 5. Holistic Candidate Profile Radar */}
        <motion.div variants={cardVariants}>
          <RadarChartCard radarScores={data.radarScores || {}} />
        </motion.div>

        {/* 6. Target Job Description Match */}
        <motion.div variants={cardVariants}>
          <ResumeMatchSection
            resumeMatch={data.resumeMatch ?? data.jobMatch ?? data.overallScore ?? 85}
            potentialMatch={data.potentialMatch ?? Math.min(100, (data.resumeMatch ?? data.overallScore ?? 85) + 7)}
            matchedSkills={data.matchedSkills || []}
            missingSkills={data.missingSkills || []}
            matchedKeywords={data.matchedKeywords || []}
            missingKeywords={data.missingKeywords || []}
          />
        </motion.div>

        {/* 7. Resume Improvement Simulator */}
        <motion.div variants={cardVariants} id="improvement-simulator">
          <ImprovementSimulator data={data} />
        </motion.div>

        {/* 8. AI Recruiter Persona */}
        <motion.div variants={cardVariants}>
          <RecruiterPersonaCard recruiterPersona={data.recruiterPersona || {}} />
        </motion.div>

        {/* 9. Recruiter Sticky Notes */}
        <motion.div variants={cardVariants}>
          <RecruiterNotesCard recruiterNotes={data.recruiterNotes || []} />
        </motion.div>

        {/* 10. AI Senior Interviewer Question Bank */}
        <motion.div variants={cardVariants}>
          <InterviewQuestionsCard interviewQuestions={data.interviewQuestions || []} />
        </motion.div>

        {/* 11. Tier-1 Tech Giant Company Readiness */}
        <motion.div variants={cardVariants}>
          <CompanyReadinessCard companyReadiness={data.companyReadiness || []} />
        </motion.div>

        {/* 12. Recruitment Execution Timeline */}
        <motion.div variants={cardVariants}>
          <RecruiterTimeline />
        </motion.div>

        {/* 13. Comprehensive Recruiter Feedback */}
        <motion.div variants={cardVariants}>
          <RecruiterFeedbackCard
            strengths={data.strengths || []}
            weaknesses={data.weaknesses || []}
            recruiterFeedback={data.recruiterFeedback || ''}
          />
        </motion.div>

        {/* 14. High-Impact Bullet Point Rewrites */}
        <motion.div variants={cardVariants}>
          <BulletImprovementsCard bulletImprovements={data.bulletImprovements || []} />
        </motion.div>

        {/* 15. Section-by-Section Analysis */}
        <motion.div variants={cardVariants}>
          <SectionAnalysisCard sectionAnalysis={data.sectionAnalysis || {}} />
        </motion.div>
      </div>
    </motion.div>
  );
};
